### ISSUE TITLE
Minor error in drivers list: RP2040 ganged/auto square

### ISSUE THREAD

**Issue by phil-barrett** [grblHAL/drivers#3]
There is a note on the main drivers page in the RP2040 colum that it does not support ganged/autosquare.  I believe that is incorrect as I have been building (vie the web builder) ganged/autosquared configurations.  Testing shows the ganged motor outputs are operating together.

**Comment by terjeio** [comment]
Yes, ganging/auto squaring is supported now. Update commited.
